### ISSUE TITLE
FR: Automatically Suggest Sentence Completions

### ISSUE THREAD

**Issue by chrisgrieser** [jmilldotdev/obsidian-gpt#3]
Just for transparency, this is essentially the same FR I also made for the text generator plugin; I am making the FR here as well, just in case only one of the two of you is interested in implementing this.
https://github.com/nhaouari/obsidian-textgenerator-plugin/issues/100

---

So as opposed to the _on-demand_ suggestions currently offered by this plug, AI-generated text could also be suggested automatically via [`EditorSuggest`](https://marcus.se.net/obsidian-plugin-docs/reference/typescript/classes/EditorSuggest). From a few weeks of trying out various AI plugins in the code editor, I found them to be actually more useful than manually prompting GPT.

Take this example from using OpenAI in neovim, where it completes a sentence without me prompting it to do so:
![CleanShot 2023-02-28 at 15 07 44](https://user-images.githubusercontent.com/73286100/221879071-21cadbc0-69d3-4551-9b15-12b7074ca744.png)

As such a feature would require a high number of API calls, it should probably be restricted to a lower number of tokens per call. In my view, only completing a sentence might make most sense.

**Comment by jmilldotdev** [comment]
Unlikely I am going to add this.
