### ISSUE TITLE
FR: Tag Prompt support for Chat Completion

### ISSUE THREAD

**Issue by Akifyss** [jmilldotdev/obsidian-gpt#4]
Hi, I really like this awesome plugin that makes it ture for me to chat with AI in obsidian.

In Chat Completion mode, is it possible to make each chat prompt could be tagged? This could make it more like a chat UI.

![image](https://user-images.githubusercontent.com/23567154/222966021-f2ae4561-59f7-4221-a42a-1e988067a216.png)
![image](https://user-images.githubusercontent.com/23567154/222965194-ae569928-b8bf-4807-af8c-0d3e6385cf6a.png)

**Comment by msguerra74** [comment]
A toggle for this would be good because I actually prefer the cleaner text-only layout that it currently has.

**Comment by Akifyss** [comment]
> A toggle for this would be good because I actually prefer the cleaner text-only layout that it currently has.

Sure, I just wish it would be a customizable option

**Comment by jmilldotdev** [comment]
Added in 1.2.0

**Comment by msguerra74** [comment]
This doesn't seem to be working as expected. I set it to wrap the chat prompt with "==" and separate the chat completions with "---", which seems to work fine for the first prompt. As I add more prompts below, it adds the opening prompt wrapper to the top of the page, while adding the closing prompt wrapper to the correct spot. Here's an example so you can see what happens after 2 prompts:

```
====What is 2+2?==

---

4.

---

What is the square root of 9?==

---

3.

---


```

Am I right to expect the wrapper to wrap every new prompt, or is this meant to only work when there's a single prompt on the page?

I don't know if I'll actually use this, but I kind of like having the questions highlighted, so I can quickly scan the document for prompts.
